=== tomqsm/xml-storage/src/main/resources/report.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://biz.letsweb.xml.storage/schemas"
           attributeFormDefault="unqualified" elementFormDefault="qualified" version="1.0" 
           xmlns="http://biz.letsweb.xml.storage/schemas report.xsd"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="report">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="stats">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:int" name="blockers"/>
                            <xs:element type="xs:int" name="critical"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="project" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="week" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:double" name="unit"/>
                                        <xs:element type="xs:double" name="overall"/>
                                        <xs:element type="xs:int" name="blockers"/>
                                        <xs:element type="xs:int" name="critical"/>
                                    </xs:sequence>
                                    <xs:attribute type="xs:int" name="number" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="name" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
<!--http://www.freeformatter.com/xsd-generator.html-->

=== tomqsm/xml-storage/src/main/resources/report.xml
<?xml version="1.0" encoding="UTF-8"?>
<report xmlns="http://biz.letsweb.xml.storage/schemas"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://biz.letsweb.xml.storage/schemas report.xsd">
    <stats>
        <week number="24">
            <blockers>9</blockers>
            <critical>0</critical>
        </week>
        <week number="24">
            <blockers>9</blockers>
            <critical>0</critical>
        </week>
    </stats>
    <project name="projekt0">
        <week number="2">
            <unit>32.2</unit>
            <overall>12.1</overall>
            <blockers>1</blockers>
            <critical>0</critical>
        </week>
        <week number="2">
            <unit>32.2</unit>
            <overall>12.1</overall>
            <blockers>1</blockers>
            <critical>0</critical>
        </week>
    </project>
    <project name="projekt1">
        <week number="2">
            <unit>32.2</unit>
            <overall>12.1</overall>
            <blockers>1</blockers>
            <critical>0</critical>
        </week>
        <week number="2">
            <unit>32.2</unit>
            <overall>12.1</overall>
            <blockers>1</blockers>
            <critical>0</critical>
        </week>
    </project>
</report>
<!--http://stackoverflow.com/questions/3965357/xml-how-to-reference-a-xsd-file-at-xml-file-->
